namespace FC.Engine.Domain.Entities;

public class DataProcessingActivity
{
    public int Id { get; set; }
    public string ModuleCode { get; set; } = string.Empty;
    public string ActivityName { get; set; } = string.Empty;
    public string Purpose { get; set; } = string.Empty;
    public string LegalBasis { get; set; } = "LegalObligation";
    public string DataCategories { get; set; } = "[]";
    public string DataSubjects { get; set; } = "[]";
    public string RetentionPeriod { get; set; } = "7 years from submission";
    public string? ThirdPartySharing { get; set; }
    public string SecurityMeasures { get; set; } = "[]";
    public bool IsAutoGenerated { get; set; } = true;
    public DateTime LastUpdated { get; set; } = DateTime.UtcNow;
}
